architecture-beta
    group platform(cloud)[Broker de Acceso]

    service frontend(internet)[Frontend Web] in platform
    service api(server)[API Backend] in platform
    service storage(database)[BD Interna] in platform

    frontend:R -- L:api
    api:R -- L:storage
